name: Deploy and Send Slack Message

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Slack Messenger
        uses: joshmgross/send-slack-message@v1.0.2

      - name: Notify Slack
        uses: slack/webhook@v3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: laravel
          text: "Deployment successful!"

