name: Deploy and Send Slack Message

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack
        uses: slack/webhook@v1
        env:
          SLACK_WEBHOOK: ${{ secrets.slack.com/services/T054L2KFP1A/B054EKU72AZ/9pao2JszDmHK9F0PmL6fj1jT }}
        with:
          channel: laravel
          text: "Deployment successful!"

