name: Send Slack Message
on:
  push:
    branches:
      - main

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
      - uses: slack/webhook@v1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: laravel
          text: "Hello from GitHub Actions!"
