name: Deploy and Send Slack Message

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # additional steps to build and deploy your application

      - name: Notify Slack
        uses: slack/webhook@v1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: laravel
          text: "Deployment successful!"

