name: Send Slack Message
on:
  push:
    branches:
      - main

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: slack/webhook@v1
        env:
          SLACK_WEBHOOK: ${{ secrets.https://hooks.slack.com/services/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 }}
        with:
          channel: general
          text: "Hello from GitHub Actions!"
